baseURL = "https://www.williamnye.co.uk/"
languageCode = "en-gb"
title = "Will Nye - The SEO Guy"
description = "Sporadic SEO related ramblings from Will Nye. A Senior SEO Consultant based in London."
theme = "aglaus"
defaultContentLanguage = "en"

googleAnalytics = "UA-58543053-1"
