baseURL = "https://www.williamnye.co.uk/"
languageCode = "en-gb"
title = "Will Nye - The SEO Guy"
theme = "aglaus"
defaultContentLanguage = "en"

googleAnalytics = "UA-58543053-1"

[outputs]
home = [ "HTML", "RSS", "REDIR", "HEADERS" ]

[mediaTypes]
[mediaTypes."text/netlify"]
suffix = ""
delimiter = ""

[outputFormats]
[outputFormats.REDIR]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true
