[context.production.environment]
  HUGO_VERSION = "0.37"
  
[[redirects]]
  from = "/category/technical/"
  to = "/categories/technical/"
  status = 301
  force = false
  
[[redirects]]
  from = "/category/content-outreach/"
  to = "/categories/content--outreach/"
  status = 301
  force = false
  
  [[redirects]]  
  from = "/category/reviews-tutorials/"
  to = "/categories/reviews--tutorials/"
  status = 301
  force = false

  [[redirects]]  
  from = "/tags/"
  to = "/"
  status = 301
  force = false
  
  [[headers]]
   for = "/*"
    [headers.values]
     Link: <https://fonts.gstatic.com>; rel=preconnect; crossorigin
